In [1]:
import numpy as np

In [7]:
from numpy import transpose

In [9]:
#Matrix
x = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])

In [10]:
#Inversion
inverse = np.linalg.inv(x)
print(f'Inversion of x = {inverse}')


Inversion of x = [[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [15]:
# Transpose
transpose=np.transpose(x)
print(f'Transpose of x = {transpose}')

Transpose of x = [[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [16]:
#Determinant
determinant = np.linalg.det(x)
print(f'Determinant of x = {determinant}')

Determinant of x = 0.2299999999999999


In [17]:
#Decomposition
values, vectors = np.linalg.eig(x)
print(f'Decomposition = {values}')
print(f'Decomposition = {vectors}')


Decomposition = [2.04100779 0.82188052 0.13711169]
Decomposition = [[-0.43721717 -0.85359707 -0.28321933]
 [-0.59931898  0.51133314 -0.61591816]
 [-0.67056536  0.09955128  0.73514055]]
